# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - feature
      - develop
      - hotfix

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.0.1'
          java-package: jdk
          architecture: x64
      
      
      - name: Compile Java file to 'out' directory
        run: javac ./src/engine/*.java ./src/entity/*.java ./src/screen/*.java -d ./out

      - name: Copy resource file to compliled folder
        run: cp -R res/ ./out/
      
      - name: Make an executable jar file
        run: jar cvfm invaders.jar ./src/META-INF/MANIFEST.MF -C ./out/ .

      - name: Upload jar file to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./invaders.jar
          asset_name: invaders.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "Automated release. Please edit this description."
